version: "3.8"
services:
  api:
    build: ./api
    env_file:
      - "./api/.env.dev"
    container_name: climate-hist-api-c
    ports:
      - "9999:9999"
    volumes:
      - ./api:/climate-hist/api
      - /climate-hist/api/node_modules
  client:
    build: ./frontend
    container_name: climate-hist-client-c
    ports:
      - "3000:3000"
    depends_on:
      - api
    stdin_open: true
    tty: true
